### ISSUE TITLE
Category Field on RSD Creation Page does not display selection feedback consistent with the other fields

### ISSUE THREAD

**Issue by DMSaunders** [wgu-opensource/osmt#113]
When adding data to a field, normally you type in text, hit enter (or select from the drop down list) and then the term appears below the field in a new box with an x next to it (delete option). The category field does not change even if you hit enter, making it seem like the data was not accepted, even though it is. 

<img width="634" alt="Screen Shot 2022-01-05 at 5 54 54 PM" src="https://user-images.githubusercontent.com/37890092/148315902-f99748d6-bd16-4683-9703-33ad5fae1f03.png">

**Comment by Corpratespaz** [comment]
This has been fixed in #327
