### ISSUE TITLE
List skills across collections

### ISSUE THREAD

**Issue by berthelemy** [wgu-opensource/osmt#160]
As an OSMT user, I would like to see skills from multiple collections, which have common categories, keywords or occupations.

**Comment by Corpratespaz** [comment]
This feature might be addressed by https://github.com/wgu-opensource/osmt/pull/312 on Develop. @berthelemy could you please test the latest Develop branch to determine if the Filters feature satisfies your request?

**Comment by Corpratespaz** [comment]
Addressed by adding filters to RSDs library enhancement #312 . Please reopen if this does not adequately suffice.
