### ISSUE TITLE
Show existing RSD when similarity warning is given

### ISSUE THREAD

**Issue by DMSaunders** [wgu-opensource/osmt#168]
### Describe the feature request or enhancement you'd like
When a warning is given that an RSD will be very similar to an existing RSD, show the existing RSD

### Is your feature request related to a problem? Please describe it.
Otherwise, there is no info for me to make the decision if I should proceed and create or stop. If I am accidentally creating an identical RSD, I may want to stop, if I am making one that is similar but different enough, I may want to proceed.

For each RSD, show me my proposed RSD name and skill statement next to the similar one's name, skill statement, author, and publication status, at minimum, and any other data that makes sense for the UI. This should happen for bulk upload and manual creation.

### Additional context
![Screen Shot 2022-02-24 at 4 45 42 PM](https://user-images.githubusercontent.com/37890092/155632393-447318fb-5c8d-4049-8f6b-2ccd03236e23.png)

**Comment by JohnKallies** [comment]
For context, similarity checking relies on ElasticSearch. There may be opportunities to get better insight from that response. See CustomRichSkillQueriesImpl.findSimilar.
