### ISSUE TITLE
Collections not exporting to CSV

### ISSUE THREAD

**Issue by arblackwell1** [wgu-opensource/osmt#178]
### Describe the bug
Two collections in the OSMT Collab instance are not currently downloading as CSV. There are five published collections total at this time, and the other three collections are able to be downloaded successfully. I cannot find any discernible difference between the collections except that the two that won't download happen to be slightly larger than the other three.

### To Reproduce
1. Go to 'osmtcollab.openskillsnetwork.com/collections'
2. Click on 'Research' collection
3. Click 'View Published Collection'
4. Click 'Download CSV'
5. Application fails to respond

### Expected behavior
When the 'Download CSV' button is clicked, the collection should successfully download via CSV.

### Screenshots
![image](https://user-images.githubusercontent.com/69263033/157343643-5162d436-d618-4e9f-b619-616634e25d57.png)

#### Desktop (please complete the following information):
 - OS: Mac Big Sur
 - Browser: Chrome
 - Version: Version 98.0.4758.109

**Comment by DMSaunders** [comment]
@JohnKallies @arblackwell1 Any update here? We have told collabs they must download their materials by the end of the month.

**Comment by JohnKallies** [comment]
I am actively working on this. We don't yet know why the experts feel, but I've pulled the data local, and I'm working through it. Either way, we've got a copy of the data and we will figure out how to get them exports.
