### ISSUE TITLE
"Back to Collection" Button

### ISSUE THREAD

**Issue by arblackwell1** [wgu-opensource/osmt#180]
### Describe the feature request or enhancement you'd like
As a skills architect, when I am viewing a single RSD within my collection, I want to be able to return to the spot I was previously at within my collection so that I don't have to do unnecessary scrolling or paging to get back to where I was.

### Is your feature request related to a problem? Please describe it.
When I'm viewing and editing skills in my collection, I want to be able to click a button that takes me back to the spot I was at within my collection. If I click the back button when viewing a single RSD, it takes me back to the top of the collection. If I edit an individual RSD within my collection and click the back button, it makes me move back through the editing screen to the collection, and then also takes me to the top of the collection rather than back to the spot I was at. This feature enhancement would limit clicks and having to navigate through different pages of the collection when trying to work with skills from that collection.

**Comment by JohnKallies** [comment]
@psanchez-wgu believes this is fixed.
