### ISSUE TITLE
Return to search results

### ISSUE THREAD

**Issue by arblackwell1** [wgu-opensource/osmt#182]
### Describe the feature request or enhancement you'd like
As a skills architect, when I open an individual RSD from my search results, I want to be able to return to my search results so that I can avoid having to complete the same search repeatedly/avoid unnecessary scrolling/paging to find where I left off.

### Is your feature request related to a problem? Please describe it.
When I search for RSDs and then open an RSD from my search results, I'm not able to page back to my search results. Instead, I have to complete the search again to generate the results and find where I left off. This is incredibly cumbersome for users who are trying to locate and review RSDs to work with/add to collections.

**Comment by JohnKallies** [comment]
Resolved in https://github.com/wgu-opensource/osmt/issues/182
