### ISSUE TITLE
More options for filtering/sorting RSDs in list view

### ISSUE THREAD

**Issue by arblackwell1** [wgu-opensource/osmt#183]
### Describe the feature request or enhancement you'd like
As a skills architect, I want additional options to filter and sort RSDs in a list view so that I can more quickly locate the RSDs I want to work with.

### Is your feature request related to a problem? Please describe it.
Currently, the only options for filtering and sorting in a list view are by status (draft, published, archived) and sorting alphabetically by category and skill name. This does not provide enough options for quickly locating the RSDs to work on. 

### Additional context
Discovery should be conducted with users to determine the best filtering/sorting parameters to add.

**Comment by JohnKallies** [comment]
This enhancement will be done by the Open Source Engineering team within WGU

**Comment by jchavez137** [comment]
Resolved by https://github.com/wgu-opensource/osmt/pull/312
Jira Ticket: https://projects.wgu.edu/browse/OSMT-12
