### ISSUE TITLE
Quick start issues

### ISSUE THREAD

**Issue by hlallo-mind** [wgu-opensource/osmt#184]
Anyone seeing this error when trying to install the quick start. 

java.util.concurrent.ExecutionException: java.net.UnknownHostException: osmt_quickstart_elasticsearch_1: Name or service not known
osmt_quickstart-app-1            | 	at org.apache.http.concurrent.BasicFuture.getResult(BasicFuture.java:71) ~[httpcore-4.4.14.jar!/:4.4.14]
osmt_quickstart-app-1            | 	at org.apache.http.concurrent.BasicFuture.get(BasicFuture.java:84) ~[httpcore-4.4.14.jar!/:4.4.14]
osmt_quickstart-app-1            | 	at org.apache.http.impl.nio.client.FutureWrapper.get(FutureWrapper.java:70) ~[httpasyncclient-4.1.4.jar!/:4.1.4]
osmt_quickstart-app-1            | 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:255) ~[elasticsearch-rest-client-7.9.2.jar!/:7.9.2]
osmt_quickstart-app-1            | 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:246) ~[elasticsearch-rest-client-7.9.2.jar!/:7.9.2]
osmt_quickstart-app-1            | 	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1613) ~[elasticsearch-rest-high-level-client-7.9.2.jar!/:7.9.2]
osmt_quickstart-app-1            | 	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1598) ~[elasticsearch-rest-high-level-client-7.9.2.jar!/:7.9.2]
osmt_quickstart-app-1            | 	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1565) ~[elasticsearch-rest-high-level-client-7.9.2.jar!/:7.9.2]
osmt_quickstart-app-1            | 	at org.elasticsearch.client.RestHighLevelClient.info(RestHighLevelClient.java:766) ~[elasticsearch-rest-high-level-client-7.9.2.jar!/:7.9.2]
osmt_quickstart-app-1            | 	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.lambda$getClusterVersion$17(ElasticsearchRestTemplate.java:413) ~[spring-data-elasticsearch-4.2.4.jar!/:4.2.4]
osmt_quickstart-app-1            | 	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.execute(ElasticsearchRestTemplate.java:383) ~[spring-data-elasticsearch-4.2.4.jar!/:4.2.4]
osmt_quickstart-app-1            | 	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.getClusterVersion(ElasticsearchRestTemplate.java:413) ~[spring-data-elasticsearch-4.2.4.jar!/:4.2.4]
osmt_quickstart-app-1            | 	at org.springframework.data.elasticsearch.core.AbstractElasticsearchTemplate.initialize(AbstractElasticsearchTemplate.java:104) ~[spring-data-elasticsearch-4.2.4.jar!/:4.2.4]
osmt_quickstart-app-1            | 	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.<init>(ElasticsearchRestTemplate.java:109) ~[spring-data-elasticsearch-4.2.4.jar!/:4.2.4]
osmt_quickstart-app-1            | 	at edu.wgu.osmt.elasticsearch.ElasticsearchClientManager.elasticsearchTemplate(ElasticsearchClientManager.kt:34) ~[classes!/:1.1.0]
osmt_quickstart-app-1            | 	at edu.wgu.osmt.elasticsearch.ElasticsearchClientManager$$EnhancerBySpringCGLIB$$cafd7b73.CGLIB$elasticsearchTemplate$4(<generated>) ~[classes!/:1.1.0]
osmt_quickstart-app-1            | 	at edu.wgu.osmt.elasticsearch.ElasticsearchClientManager$$EnhancerBySpringCGLIB$$cafd7b73$$FastClassBySpringCGLIB$$c2528524.invoke(<generated>) ~[classes!/:1.1.0]
osmt_quickstart-app-1            | 	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.10.jar!/:5.3.10]
osmt_quickstart-app-1            | 	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.10.jar!/:5.3.10]

**Comment by JohnKallies** [comment]
Hello,

Would you please paste the output of these commands in a reply? I don't foresee anything sensitive or private in that command output.

`./osmt_cls.sh -v`

`docker ps` (with your Quickstart instance started, even broken)

Hopefully we can get you moving forward. Thanks!
