### ISSUE TITLE
'Add to collection' from search results adds ALL returned RSDs to collection

### ISSUE THREAD

**Issue by JohnKallies** [wgu-opensource/osmt#189]
### Describe the bug
'Add to collection' from search results adds ALL returned RSDs to collection. It should only add the selected RSDs.

### To Reproduce
1. Create a throw-away collection. This defect may fill it with many unexpected RSDs
2. Search for RSDs and view results. Note the count.
3. Select one RSD from the list to add to your throw-away collection
4. Toast shows that all RSDs from the search results were aded to the throw-away collection

This behavior has been confirmed by WGU skills architects using OSMT

### Expected behavior
Only the selected RSD(s) should be added to a collection

#### Desktop (please complete the following information):
 - OS: Mac 
 - Browser Chrome 99 

### Additional context
@JohnKallies: I get inconsistent results trying to reproduce it.. Sometimes it adds just the selected RSDs, Other times it adds all RSD in the search result. I did get HTTP errors on the requests about the Task that performs the update

**Comment by hikr17** [comment]
Make sure to test that the 3-dot menu Add to Collection still adds only 1 skill and that the big blue Add to Collection button correctly adds only the selected skills in the following locations:
* main page
* search results page
* advanced search page

**Comment by JohnKallies** [comment]
This was resolved in PR #225
