### ISSUE TITLE
Default author isn't being applied during batch import

### ISSUE THREAD

**Issue by arblackwell1** [wgu-opensource/osmt#30]
During the batch import process in OSMT when the author field is left blank, the default value is not being applied. The default value is able to be configured as a white label parameter for OSMT so that users don't have to enter the same author every time a new RSD is created or a batch import completed. 

The expected behavior is that:
Given the Author field is configured with a default value
when a batch import is completed
the default author is applied to all RSDs in the CSV.

**Comment by JohnKallies** [comment]
@psanchez-wgu believes this is fixed.
